### PR TITLE
Change up the order of the config, fix some spelling issues

### PR DESCRIPTION
**Pull request by TheDoctorsLife**
I also made it look prettier. In my opinion these changes should make warden easier to configure, however, I can revert this back to the way it is, and just fix the spelling.

### CODE REVIEW

**Comment by LordLambda** [comment]
Sorry I don't like this at all. But it's not just my opinion. Will wait for more input.

**Comment by TheDoctorsLife** [comment]
Alright, like I said, if the main opion is unliked, I can resubmit the pr just with the spelling and grammer fixes.

**Comment by jayanratna** [comment]
I think that having the order changed is a bad idea, mainly because I feel that when I scroll to a section I don't get an overview of the options I could expect in the section(doctor's version). This is more of a UX kinda issue and I feel it should be the lambda had it, spelling and grammar can be changed, no problem.

**Comment by LordLambda** [comment]
Alright seeing as how this has been open for a while. I'm going to call it quits on people inputting their comments for now. So I'm going to close this for now, and If you want to just fix spelling, and such in a pr you can do that (I'll accept it). Also I would recommend bringing  this up later in development if you want it. As to get more peoples opinions on it.

**Pull request closed without merging**
